### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by pi43r** [Pant/nextcloudpi-readthedocs#3]
Currently all links point to the old docs. 
Example: https://github.com/nextcloud/nextcloudpi/wiki/How-to-access-from-outside-your-network

found at: http://docs.nextcloudpi.com/en/latest/Getting-Started/FAQ/

**Comment by ovpc** [comment]
Thanks for pointing out.
Assume that by " all links " you mean all links on that page. Most links have been edited or re-generated automatically.
Docs are a work in progress. ;-)
Edit: All broken links, on that FAQ, are fixed now, let us know if more are encountered, thanks.

**Comment by pi43r** [comment]
Sorry, 'all' links was a bit of an overstatement :) 
Of course I meant the internal links.

If I find more I will try to do a pull request ;)
