### ISSUE TITLE
Finding better ways to write and maintain documentation

### ISSUE THREAD

**Issue by ovpc** [Pant/nextcloudpi-readthedocs#5]
Hi Guys,

Quit a bit work has gone into moving from github wiki to readthedocs. But sorry to say, I am not happy at all with it.
I find editing very frustrating, and especially making changes to structure, which happens regularly, as we expand in functionality.

Creating and editing pages has become even more 'noob' unfriendly, as there is no visual editor any more. It's okay for me, I have learned markdown, but it will not make it easier for others to contribute.

Even a Wordpress Documentation Plugin would be better then this imho.

I created a devel branch here to see if I could edit and add a Upgrades menu item and move relevant pages, but afaik there is no way to move pages, and it would break all the links, which I can not test, as they will and need be pointing to master branch.

I really don't want to spend that much time editing and reorganizing pages on a regular base.

So I vote to: look for and move to a more suitable platform, or just return to the github wiki.

**Comment by chiyi4488** [comment]
> Even a Wordpress Documentation Plugin would be better then this imho.

> So I vote to: look for and move to a more suitable platform, or just return to the github wiki.

I like wordpress.

I don't want to go back to the GitHub Wiki, which is very poor for localization support.

**Comment by chiyi4488** [comment]
If the final vote is WordPress, I recommend lionfree.net, which is a free server provided by Taiwan University, and I am willing to assist in applying for this service. (Free plan: 1GB space, 30GB traffic, 3 databases, Never show ads)

**Comment by ovpc** [comment]
I have not said it should be Wordpress, just that file editing documentation with github is not very inviting nor easy for first time users. And suggest that we should look for another better way.

I do appreciate and am grateful for the work that has gone into this project, which was started to make localization possible and improve navigation and readability. 

I had not realized it would reduce edit possibilities to plain text with markdown. 
We still cannot restructure, move files easily, which we need to do al the time, 
Also having to manually edit broken links, of which there are a lot. 
On top of that testing the devel branch is impractical to say the least.

**Comment by chiyi4488** [comment]
> I have not said it should be Wordpress,

Yep, I know.

I mean, I think WordPress is a good choice as a documentation system.
